name: totale_reussite
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.5
  cinetpay: ^1.0.4
  sqflite: ^2.2.0+3
  file_picker: ^5.2.2
  url_launcher: ^6.1.6
  google_fonts: ^3.0.1
  social_share: ^2.2.1
  external_path: ^1.0.3
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  google_sign_in: ^5.4.2
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.0.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  pin_code_fields: ^7.4.0
  firebase_storage: ^11.0.5
  flutter_parsed_text: ^2.2.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  flutter_facebook_auth: ^5.0.6
  firebase_dynamic_links: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
